### ISSUE TITLE
Allow log stream name to be passed as a parameter in the queries

### ISSUE THREAD

**Issue by prateek1192** [gogama/incite#17]
The query feautre of incite does not let us pass the log stream name and only log group name is allowed.

https://docs.aws.amazon.com/cli/latest/reference/logs/get-log-events.html

Allows query names as well. 

It would be great if we can implement this feature.
TIA

**Comment by vcschapp** [comment]
Hi @prateek1192. Thanks for this enhancement request!

Did you know you can achieve the effect you desire using the `Text` of the query by including a filter on log stream, for example as shown below?

```
.... <Insights query> ...
| filter @logStream = "my logstream name"
```

Two CWL docs pages I'd recommend for this are:

- [CloudWatch Logs Insights query syntax](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax.html)
- ...which links to [Supported logs and discovered fields](https://docs.aws.amazon.com/en_us/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData-discoverable-fields.html)
- ...which documents the five "system" fields `@message`, `@timestamp`, `@ingestionTime`, `@logStream`, and `@log`.

**Comment by vcschapp** [comment]
@prateek1192, following up: Did you see my previous message, and can you confirm whether this works to solve your use case?

**Comment by prateek1192** [comment]
Thanks @vcschapp , I tried it out and it solves my use case. Appreciate the help !

**Comment by vcschapp** [comment]
Awesome. So glad to hear it!
