### ISSUE TITLE
Use custom User-Agent when sending HTTP requests to CloudWatch Logs API

### ISSUE THREAD

**Issue by vcschapp** [gogama/incite#18]
# User Story

As an application developer, I want the AWS CloudWatch Logs team to be aware of how much usage comes from Incite.

# Notes

This can be accomplished fairly trivially with the the AWS SDK for Go v1 using the [`request.AddToUserAgent(...)`](https://docs.aws.amazon.com/sdk-for-go/api/aws/request/#AddToUserAgent) free function.

**Comment by alvin-rw** [comment]
Hi @vcschapp , can I work on this?

**Comment by vcschapp** [comment]
Hi @alvin-rw, please feel free to take this on. I will assign the issue over to you.

I just pushed some WIP I had been building towards this, namely a new internal function named `version()` (see commit `f36491f` [here](https://github.com/gogama/incite/commit/f36491f6cf572ac77616b9213d2f9e384a02dd95) and source code [here](https://github.com/gogama/incite/blob/main/version.go#L19-L40)). You can append the output of `version()` to the `User-Agent` header for each type of request Incite currently makes to the Insights API (`StartQuery`, `StopQuery`, `GetQueryResults`).

**Comment by alvin-rw** [comment]
Hi @vcschapp , I've updated the code to use custom User-Agent header.
Please check the PR #21  for detailed information and please tell me if I should change anything.

**Comment by vcschapp** [comment]
Merged Pull Request #21.

Thanks @alvin-rw.
