### ISSUE TITLE
Improve documentation about chunks, chunked queries, and Incite differentiators

### ISSUE THREAD

**Issue by vcschapp** [gogama/incite#20]
# User Story

As an application developer, I want to understand how *chunked queries* work so I can better understand whether they are suitable for my use case.

# Notes

## Chunks and chunked queries

In [issue #16](https://github.com/gogama/incite/issues/16), @[lloyd-fftrf](https://github.com/lloyd-fftrf) gave some feedback on improving the documentation around chunked queries. He wrote:

> Can you help me explain what's the difference between Chunk and SplitUntil? I've tried reading the documentation but I don't seem to get the difference
>
> ...
>
> ... For me, I got confused at the first sentence of the Chunk documentation. I kind of not sure what chunked query meant. I think it would be better if the definition of the chunked query is written right after the first sentence. Like below:
>
> ```go
> // Chunk optionally requests a chunked query and indicates the chunk
> // size.
> 
> // In a chunked query, each chunk is sent to the CloudWatch Logs
> // service as a separate Insights query. This can help large queries
> // complete before the CloudWatch Logs query timeout of 15 minutes,
> // and can increase performance because chunks can be run in parallel.
> 
> // If Chunk is zero, negative, or greater than the difference ...
> ```

👆 Here the middle paragraph is @lloyd-fftrf's suggestion for improvement.

## Incite differentiators

The Incite `README.md` sometimes buries the lede or doesn't explain Incite's benefits well enough. As examples, it doesn't clarify that *you don't need to poll*; and that it makes the *query concurrency limit go away*; and that it *makes the result limit go away*. It should be re-examined with a critical eye and a view to making the benefits pop.

**Comment by lloyd-fftrf** [comment]
Hi @vcschapp , just want to clarify that here I didn't write the middle paragraph. The definition of the chunked query is already in the documentation, but it was placed after the usage guide paragraph. My suggestion was only to move the definition before the usage. 

Here is the original documentation
> ...
>	// Chunk optionally requests a chunked query and indicates the chunk
>	// size.
>	//
>	// If Chunk is zero, negative, or greater than the difference
>	// between End and Start, the query is not chunked. If Chunk is
>	// positive and less than the difference between End and Start, the
>	// query is broken into n chunks, where n is (End-Start)/Chunk,
>	// rounded up to the nearest integer value. If Chunk is positive, it
>	// must represent a whole number of milliseconds (cannot have
>	// sub-millisecond granularity).
>	//
>	// In a chunked query, each chunk is sent to the CloudWatch Logs
>	// service as a separate Insights query. This can help large queries
>	// complete before the CloudWatch Logs query timeout of 15 minutes,
>	// and can increase performance because chunks can be run in parallel.
>	// However, the following considerations should be taken into account:
>	//
>	// • In a chunked query, Limit applies separately to each chunk. So
>	// a query with 50 chunks and a limit of 50 could produce up to 2500
>	// final results.
>	//
>	// • If Text contains a sort command, the sort will only apply
>	// within each individual chunk. If the QuerySpec is executed by a
>	// QueryManager configured with a parallelism factor above 1, then
>	// the results may appear be expected of order since the order of
>	// completion of chunks is not guaranteed.
>	//
>	// • If Text contains a stats command, the statistical aggregation
>	// will be applied to each chunk in a chunked query, meaning up to n
>	// versions of each aggregate data point may be returned, one per
>	// chunk, necessitating further aggregation in your application
>	// logic.
>	//
>	// • In general if you use chunking with query text which implies
>	// any kind of server-side aggregation, you may need to perform
>	// custom post-processing on the results.
>	Chunk time.Duration
> ...

**Comment by vcschapp** [comment]
Got it! Thanks for the clarification @lloyd-fftrf. Your suggested reordering makes a lot of sense to me.

**Comment by vcschapp** [comment]
Commit [0d4bc94](https://github.com/gogama/incite/commit/0d4bc94a7092d873a4f9e35f5f84a6573e67c546) improves the chunks and chunked query documentation along the lines discussed with @lloyd-fftrf above. This is merged.

Still to be done: Incite differentiators and `README.md`.

**Comment by vcschapp** [comment]
Another documentation issue is revealed by issue #22 from @ryanoolala. He wasn't able to tell from the `README` how to use `Chunk` to work around the Insights 10K results limit.

**Comment by vcschapp** [comment]
Docs have been improved.
